llm:
  api_base: "https://your-company-api-endpoint"
  api_key: "your-api-key"
  model: "your-model-name"
embedding:
  api_base: "https://your-company-api-endpoint"
  api_key: "your-api-key"
  model: "your-embedding-model"
vector_store:
  type: "faiss"
  path: "vector_store/faiss_index"
